name: CI
on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags:
          - ""
          - "--no-default-features"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev
      - name: Apply rustfmt
        if: matrix.flags == '' && github.event_name == 'push'
        run: |
          cargo fmt --all
          if ! git diff --quiet; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add -- '*.rs'
            git commit -m 'style: apply rustfmt'
            git push
          fi
      - run: cargo fmt --all -- --check
      - run: cargo build --release ${{ matrix.flags }}
      - run: cargo test --release ${{ matrix.flags }}
      - run: cargo clippy --all-targets ${{ matrix.flags }} -- -D warnings
